var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                   o            ",
   "                                                o                               ",
   "                                                   xx      xx      !            ",
   "                                    o o      xx                   !!!           ",
   "                                                      o            !            ",
   "                        o o        xxxxx                               o        ",
   "                                                                                ",
   "                         s                o o                                   ",
   "              o        xxxxx                                       o         x  ",
   "                                         xxxxx                             o x  ",
   "             xxxx                                                            x  ",
   "     @ ssssssx  x       g                                   o    xxxxx   g   x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx                            xxxxxxx   xxxxxxxxx  ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
    
  ["                          x         v          v          x                     ",
   "                          x                               x                     ",
   "                          x               o               x                     ",
   "                          x             xxxxx      o      x                     ",
   "                          x                      xxxx     x                     ",
   "                          x                               x                     ",
   "                          x      o                        x                     ",
   "                          x     xxxx                      x                     ",
   "                          x                               x                     ",
   "                          x                 o             x                     ",
   "                          x                xxx            x                     ",
   "                          x                               x                     ",
   "                          x                              ox                     ",
   "                          x                             xxx                     ",
   "                          x                              =x                     ",
   "                          x                        o      x                     ",
   "                          x                       xx      x                     ",
   "                          x                               x                     ",
   "                          x                 o             x                     ",
   "                          x                xx             x                     ",
   "                          x        o                      x                     ",
   "                          x       xx                      x                     ",
   "                          x=                              x                     ",
   "                          x                               x                     ", 
   "                          x                               x                     ",
   "                          xo          v                   x                     ",
   "                          xxx                             x                     ",
   "                          x                               x                     ",
   "                          x                               x                     ",
   "                          x                               x                     ",
   "                          x                  xxxx         x                     ",
   "                          x                               x                     ",
   "                          x                               x                     ",
   "                          x                               x                     ",
   "                          x        o                      x                     ",
   "                          x      xxxxx                    x                     ",
   "                          x                              =x                     ",
   "                          x                               x                     ",
   "                          x                            o  x                     ",
   "                          x                         xxxxxxx                     ",
   "                          x                               x                     ",
   "                          x                               x                     ",
   "                          x       o           v           x                     ",
   "                          x      xxxx                     x                     ",
   "                          x                               x                     ",
   "                          x                               x                     ",
   "                          x=                              x                     ",
   "                          x                               x                     ",
   "                          x                   o           x                     ",
   "                          x                 xxxxx         x                     ",
   "                          x                               x                     ",
   "                          x                               x                     ",
   "                          x                              =x                     ",
   "                          x                               x                     ",
   "                          x o                             x                     ",
   "                          xxxxxx          |               x                     ",
   "                          x                               x                     ",
   "                          x                             o x                     ",
   "                          x                            xxxx                     ",
   "                          x               o               x                     ",
   "                          x                               x                     ",
   "                          x             xxxxxx            x                     ",
   "                          x      v                 v      x                     ",
   "                          x                               x                     ",
   "                          x             !!!!!!            x                     ",
   "                          x      o                 o      x                     ",
   "                          x                               x                     ",
   "                          x    xxxxx             xxxxx    x                     ",
   "                          x                               x                     ",
   "                          x                               x                     ",
   "                          x           g   @   g           x                     ",
   "                          x        xxxxxxxxxxxxxxx        x                     "],
  
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     ",
   "!!!!!!!!!           v     v                                  v     v      x     ",
   "!!!!!!!!!              o                                                  x     ",
   "!!!!!!!!!                                                       o         x     ",
   "!!!!!!!!!                                                               = x     ",
   "!!!!!!!!!              s                                        s         x     ",
   "!!!!!!!!!         xxxxxxxxxxx                               xxxxxxxxx     x     ",
   "!!!!!!!!!    x    !         x                               x       x     x     ",
   "!!!!!!!!!         !         x                               x       xx    x     ",
   "!!!!!!!!!         !         x                            xxxx       x     x     ",
   "!!!!!!!!!    o    !         x                               x       x  o  x     ",
   "!!!!!!!!!         !         x                               x       x     x     ",
   "!!!!!!!!x         !         x                               x       x     x     ",
   "!!!!!!xx     x    !         x                               x       x     x     ",
   "!!!xxxx           !         x xx   xxx           xxx   xx   x       x    xx     ",
   "!!!x              !         x!!!!!!!!!x         x!!!!!!!!!!xx       x     x     ",
   "!!!x              !         x!!!!!!!!!x    =    x!!!!!!!!!!xx       x  o  x     ",
   "!!!x  @           !         x!!!!!!!!!x         x!!!!!!!!!!xx       x     x     ",
   "!!!xxxxxx         !         x!!!!!!!!!!x       x!!!!!!!!!!!xx       xx    x     ",
   "!!!!!!!!!         !         x!!!!!!!!!!!       !!!!!!!!!!!!xx       x     xxxxx ",
   "!!!!!!!!!         !         x!!!!!!!!!!!       !!!!!!!!!!!!xx       x       o x ",
   "!!!!!!!!!         !         x!!!!!!!!!!x   o   !!!!!!!!!!!!xx       x         x ",
   "!!!!!!!!!         !         x!!!!!!!!!!x       !!!!!!!!!!!!xx       xsssxxxxxxx ",
   "!!!!!!!!!   xx    !         x!!!!!!!!!!xx      !!!!!!!!!!!xxx                   ",
   "!!!!!!!!!         !         x!!!!!!!!!!x       !!!!!!!!!!!xxx                   ",
   "!!!!!!!!!         !         x!!!!!!!!!!x       !!!!!!!!!!!xxx                   ",
   "!!!!!!!!!    o    !         x!!!!!!!!!!!   o   x!!!!!!!!!!xxx                   ",
   "!!!!!!!!!         !         x!!!!!!!!!!!       x!!!!!!!!!!xxx                   ",
   "!!!!!!!!!         !         x!!!!!!!!!!!       x!!!!!!!!!!xxx                   ",
   "!!!!!!!!!   xxx   !         x!!!!!!!!!!!      xx!!!!!!!!!!xxx                   ",
   "!!!!!!!!!         !         x!!!!!!!!!!!       x!!!!!!!!!!xxx                   ",
   "!!!!!!!!!!!!!!!!!!!         x!!!!!!!!!!!       !!!!!!!!!!!xxx                   ",
   "!!!!!!!!!!!!!!!!!!!         x!!!!!!!!!!!   o   !!!!!!!!!!!xxx                   ",
   "!!!!!!!!!!!!!!!!!!!         xxxxxxxxxxx!ssxxxss!xxxxxxxxxxxxx                   "],
 
  
   
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
